---
## This playbook installs and configures AD authentication

- name: Install and configure AD authentication
  hosts: all
  remote_user: root

  tasks:
    - name: create tmp directory
      shell: /bin/bash -c "mkdir /mnt/tmp"
      ignore_errors: yes

    - name: mount groups share
      shell: /bin/bash -c "mount -t cifs //nl19fs002/install -o username=_svc_compadd,domain=G-STAR.RAW,password=R@wadd00 /mnt/tmp"
     
    - name:  copy VMWARE Tools Installation
      shell: /bin/bash -c "cd /mnt/tmp/Server/Linux"
      
    - name: create /tmp 
      shell: /bin/bash -c "mkdir /tmp"
      ignore_errors: yes
      
    - name: copy VMWare Tools Installation
      shell: /bin/bash -c "cp /mnt/tmp/Server/Linux/VMwareTools-9.0.15-2323214.tar.gz /tmp"
      ignore_errors: yes
      
    - name: untar and run
      shell: /bin/bash -c "tar -zxvf /tmp/VMwareTools-9.0.15-2323214.tar.gz -C /tmp/"
      ignore_errors: yes
    
    - name: run the vmware installer
      shell: /bin/bash -c "/tmp/vmware-tools-distrib/vmware-install.pl -d default"
      
    - name: installs tools needed for joining domain
      yum: name={{ item }} state=installed
      with_items:
        - authconfig
        - krb5-workstation
        - pam_krb5
        - samba-common
        - oddjob-mkhomedir
        - ntp
        - sudo
        
    - name: run authconfig and set up the required settings and files
      shell: /bin/bash -c "authconfig --disablecache --enablewinbind --enablewinbindauth --smbsecurity=ads --smbworkgroup=GSTARRAW --smbrealm=G-STAR.RAW --enablewinbindusedefaultdomain --winbindtemplatehomedir=/home/G-STAR.RAW/%U --winbindtemplateshell=/bin/bash --enablekrb5 --krb5realm=G-STAR.RAW --enablekrb5kdcdns --enablekrb5realmdns --enablelocauthorize --enablemkhomedir --enablepamaccess --updateall"
      
    - name: join domain
      shell: /bin/bash -c "net ads join g-star.raw -U _svc_compadd%R@wadd00"
    
    - name: mkdir /home/g-star.raw
      shell: mkdir /home/g-star.raw
      ignore_errors: yes
      
    - name: change permissions on the folder
      shell: chmod 777 /home/g-star.raw
      ignore_errors: yes
      
      
    - name: add group to sudoers 
      shell: echo "%rdp-$HOSTNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      
    - name: Update PAM sshd files
      shell: |
        echo '#%PAM-1.0
        auth       required     pam_sepermit.so
        auth       required     pam_sepermit.so
        auth       sufficient   pam_winbind.so
        auth       include      system-auth
        account    required     pam_nologin.so
        account    include      password-auth
        account    include      system-auth
        password   include      password-auth
        password   include      system-auth
        # pam_selinux.so close should be the first session rule
        session    required     pam_selinux.so close
        session    required     pam_loginuid.so
        # pam_selinux.so open should only be followed by sessions to be executed in the user context
        session    required     pam_selinux.so open env_params
        session    required     pam_namespace.so
        session    optional     pam_keyinit.so force revoke
        session    include      password-auth
        session    include      system-auth' > /etc/pam.d/sshd
        
    - name: Update PAM systemauth
      shell: |
        echo '#%PAM-1.0 
        # This file is auto-generated. 
        # User changes will be destroyed the next time authconfig is run. 
        auth required pam_env.so 
        auth sufficient pam_unix.so nullok try_first_pass 
        auth requisite pam_succeed_if.so uid >= 500 quiet 
        auth sufficient pam_krb5.so use_first_pass 
        auth sufficient pam_winbind.so use_first_pass 
        auth required pam_deny.so

        account required pam_access.so 
        account required pam_unix.so broken_shadow 
        account [default=ignore success=1] pam_succeed_if.so uid < 16777216 quiet 
        account [default=bad success=ignore] pam_succeed_if.so user ingroup rdp-$HOSTNAME quiet 
        account sufficient pam_localuser.so 
        account sufficient pam_succeed_if.so uid < 500 quiet 
        account [default=bad success=ok user_unknown=ignore] pam_krb5.so 
        account [default=bad success=ok user_unknown=ignore] pam_winbind.so 
        account required pam_permit.so

        password requisite pam_cracklib.so try_first_pass retry=3 
        password sufficient pam_unix.so md5 shadow nullok try_first_pass use_authtok 
        password sufficient pam_krb5.so use_authtok 
        password sufficient pam_winbind.so use_authtok 
        password required pam_deny.so

        session optional pam_keyinit.so revoke 
        session required pam_limits.so 
        session optional pam_mkhomedir.so 
        session [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid 
        session required pam_unix.so 
        session optional pam_krb5.so 
        ' > /etc/pam.d/system-auth
